import Footer from '@/components/footer'
import type { Metadata } from 'next'
import NavBar from '../components/navBar'
import './globals.scss'



export const metadata: Metadata = {
  title: 'Rick and Morti',
  description: 'Generated by Rick and Morti',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  )
}
