import type { Metadata } from 'next'
import './globals.scss'


export const metadata: Metadata = {
  title: 'Rick and Morti',
  description: 'Generated by Rick and Morti',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
